### ISSUE TITLE
use Google satellite pictures as background in Netedit and in SUMO Gui

### ISSUE THREAD

**Issue by behrisch** [openmobility-wg/userstories#1]
**As a**
Advanced user

**I want to**
use Google satellite pictures as background in Netedit and in SUMO Gui

**In order to**
- ease map editing work in case of real world scenarios
- create such simulations, where the vehicles move 'likely' on the real world roads

**Acceptance criteria**
if there is a geo-referenced network loaded in Netedit or SUMO Gui, I can choose Google satellite pictures as background, as an alternative of background decals

**Comment by behrisch** [comment]
This is related to eclipse/sumo#4786

**Comment by ZoltanBaksa** [comment]
We have created a possible way to use any kind of map tile server. The suggested solution would contain a few input boxes, where the user can enter his/her url to map server, user ID, password, or API key, which enables to use the tiles without legal consequences, requested zoom level, geo boundary, etc...
The next step would be to download the necessary tiles into a dedicated folder, to reuse it later. There shall be a check-box to control the visibility of such map tiles, to be able to switch on-off during netedit usage, and to be able to layer it under the other pictures loaded by decal configuration.

**Comment by behrisch** [comment]
We decided on today's meeting in Ludwigsburg to start with this one, since it is clearly defined, has a good visiiblity and has the potential too deliver fast results and a good showcase on how trhe user story process works.

**Comment by behrisch** [comment]
> We have created a possible way to use any kind of map tile server.

@ZoltanBaksa Does this mean you already have an implementation we can use?

**Comment by behrisch** [comment]
We now implemented a basic version of the functionality as a python script, see the commits in eclipse/sumo#6279. Unfortunately it is not in the release but the script is more or less standalone, just download it from https://raw.githubusercontent.com/eclipse/sumo/master/tools/tileGet.py and put it in the tools dir.

**Comment by Vickey-ZWQ** [comment]
I have downloaded and run the "tileGet.py" script in VScode.  And I got an error below. I'm confused about the steps of using the script,  I don't have any input boxes. Please help! By the way, the system I use is Windows 10, and the version of Python is 3.7, finally, sumo's version is 1.3.1.

     PS D:\WorkSpace\SUMO\user-programs> cd 'd:\WorkSpace\SUMO\user-programs'; ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONU,NBUFFERED}='1'; & 'D:\APP\Python\python.exe' 'c:\Users\admin\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\ptvsd_launcher.py' '--default' '--client' '--host' 'localhost' '--port' '54393' 'd:\WorkSpace\SUMO\user-programs\tileGet.py' Usage: tileGet.py [options]
**tileGet.py: error: At least one of 'bbox' and 'net' and 'polygon' has to be set.**
PS D:\WorkSpace\SUMO\user-programs>

**Comment by behrisch** [comment]
There are no input boxes yet, please have a look at the docs for an example https://sumo.dlr.de/docs/Tools/Misc.html#tilegetpy

**Comment by behrisch** [comment]
Has been considered completed by the working group.
